package com.company.NetSDK;

import java.io.Serializable;

/**
 * \if ENGLISH_LANG
 * {@link INetSDK#OperateFaceRecognitionDB} input parameter
 * \else
 * {@link INetSDK#OperateFaceRecognitionDB} 接口输入参数
 * \endif
 */
public class NET_IN_OPERATE_FACERECONGNITIONDB implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * \if ENGLISH_LANG
     * Type of operation, refer to {@link EM_OPERATE_FACERECONGNITIONDB_TYPE}
     * \else
     * 操作类型, 参考 {@link EM_OPERATE_FACERECONGNITIONDB_TYPE}
     * \endif
     */
    public int                                emOperateType;

    /**
     * \if ENGLISH_LANG
     * Personnel information
     * \else
     * 人员信息
     * \endif
     */
    public FACERECOGNITION_PERSON_INFO        stPersonInfo = new FACERECOGNITION_PERSON_INFO();

    ///// emOperateType操作类型为 NET_FACERECONGNITIONDB_DELETE_BY_UID 时使用,stPeronInfo字段无效 /////
    /**
     * \if ENGLISH_LANG
     * Person unique mark. Generated by the client if it is the first time. Different from the ID string.
     * the space application by the user, apply to sizeof(NET_UID_CHAR)*nUIDNum
     * \else
     * 人员唯一标识符,首次由服务端生成,区别于ID字段， 由用户申请内存,大小为sizeof(NET_UID_CHAR)*nUIDNum
     * \endif
     */
    public NET_UID_CHAR[]                   stuUIDs;

    ////////////////////////////////////////// 人脸图片路径+名称 //////////////////////////////////////
    /**
     * \if ENGLISH_LANG
     * Picture name
     * \else
     * 图片名称， IVSS最大支持256KB，IPC-FR最大支持150KB，且仅只支持JPG格式图片
     * \endif
     */
    public String                           pBuffer;
    ////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * \if ENGLISH_LANG
     * use stPersonInfoEx when bUsePersonInfoEx is true, otherwise use stPersonInfo
     * \else
     * 使用人员扩展信息
     * \endif
     */
    public boolean			                 bUsePersonInfoEx;

    /**
     * \if ENGLISH_LANG
     * expansion of personnel information, bUsePersonInfoEx is true, valid
     * \else
     * 人员信息扩展, bUsePersonInfoEx为true时，有效
     * \endif
     */
    public FACERECOGNITION_PERSON_INFOEX	stPersonInfoEx = new FACERECOGNITION_PERSON_INFOEX();


    public NET_IN_OPERATE_FACERECONGNITIONDB() {

    }

    /**
     * @param nUIDNum 人员唯一标识符个数
     */
    public NET_IN_OPERATE_FACERECONGNITIONDB(int nUIDNum) {
        stuUIDs = new NET_UID_CHAR[nUIDNum];
        for(int i = 0; i < nUIDNum; i++) {
            stuUIDs[i] = new NET_UID_CHAR();
        }
    }
}
